version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go test -v -p 1 -parallel 1 -failfast ./...
  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go get github.com/tcnksm/ghr
      - run: go get github.com/mitchellh/gox
      - run: mkdir dist
      - run: echo "export BUILD_TAG=$(git describe --tags)" >> $BASH_ENV
      - run: echo "export BUILD_SHA=$(git rev-parse --short HEAD)" >> $BASH_ENV
      - run: echo "export BUILD_DATE=$(date -u '+%Y/%m/%d:%H:%M:%S')" >> $BASH_ENV
      - run: gox -verbose -osarch="darwin/amd64 linux/amd64 linux/arm linux/arm64 netbsd/amd64 openbsd/amd64 freebsd/amd64" -ldflags "-X main.tag=$BUILD_TAG -X main.sha=$BUILD_SHA -X main.buildDate=$BUILD_DATE" -output "dist/sn-dotfiles_{{.OS}}_{{.Arch}}" ./...
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(git describe --tags)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} ./dist/
workflows:
  version: 2
  build-release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)/
            branches:
              only: master